Variable default hardening.  PATH Hardening. grep and sed hardening. + BUILD

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -80,33 +80,37 @@ environment:
   # file exist (branch tag, commit - pghint = "commit")
   # in the situations when pg source code is used to build plr.
 
-  - pg: master # non-static commit - from git
-    PlatformToolset: v143
-    Configuration: Debug
-    Platform: x64
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.3.1
-    compiler: msys2
+# SUCCEED
 
-  - pg: REL_16_BETA1 # static commit - from git
-    PlatformToolset: v143
-    Configuration: Debug
-    Platform: x64
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.3.1
-    compiler: msys2
+#   - pg: master # non-static commit - from git
+#     PlatformToolset: v143
+#     Configuration: Debug
+#     Platform: x64
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.3.1
+#     compiler: msys2
+# 
+#   - pg: REL_16_BETA1 # static commit - from git
+#     PlatformToolset: v143
+#     Configuration: Debug
+#     Platform: x64
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.3.1
+#     compiler: msys2
+# 
+#   - pg: none # pre-existing binary # June 2023 - postgresql 15.1
+#     PlatformToolset: v143
+#     Configuration: Release
+#     Platform: x64
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.3.1
+#     compiler: msys2
 
-  - pg: none # pre-existing binary # June 2023 - postgresql 15.1
-    PlatformToolset: v143
-    Configuration: Release
-    Platform: x64
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.3.1
-    compiler: msys2
+# Fail but should not
 
   - pg: REL_15_3
     PlatformToolset: v143
-    configuration: Debug
+    Configuration: Debug
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     rversion: 4.2.3
     compiler: msvc
@@ -118,83 +122,83 @@ environment:
     rversion: 4.2.3
     compiler: msvc
 
-  - pg: 15.3-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.1.3
-    compiler: msvc
-
-  - pg: 14.8-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.2.3
-    compiler: msvc
-
-  - pg: 14.8-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.1.3
-    compiler: msvc
-
-  - pg: 13.11-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.2.3
-    compiler: msvc
-
-  - pg: 13.11-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.1.3
-    compiler: msvc
-
-  - pg: 12.15-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.2.3
-    compiler: msvc
-
-  - pg: 12.15-2
-    PlatformToolset: v143
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
-    rversion: 4.1.3
-    compiler: msvc
-
-  - pg: 11.20-2
-    PlatformToolset: v140
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
-    rversion: 4.2.3
-    compiler: msvc
-
-  - pg: 11.20-2
-    PlatformToolset: v140
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
-    rversion: 4.1.3
-    compiler: msvc
-
-  - pg: 10.23-1
-    PlatformToolset: v120
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
-    rversion: 4.2.3
-    compiler: msvc
-
-  - pg: 10.23-1
-    PlatformToolset: v120
-    Configuration: Release
-    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
-    rversion: 4.1.3
-    compiler: msvc
-
+#   - pg: 15.3-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
+#   - pg: 14.8-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.2.3
+#     compiler: msvc
+# 
+#   - pg: 14.8-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
+#   - pg: 13.11-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.2.3
+#     compiler: msvc
+# 
+#   - pg: 13.11-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
+#   - pg: 12.15-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.2.3
+#     compiler: msvc
+# 
+#   - pg: 12.15-2
+#     PlatformToolset: v143
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
+#   - pg: 11.20-2
+#     PlatformToolset: v140
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
+#     rversion: 4.2.3
+#     compiler: msvc
+# 
+#   - pg: 11.20-2
+#     PlatformToolset: v140
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
+#   - pg: 10.23-1
+#     PlatformToolset: v120
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
+#     rversion: 4.2.3
+#     compiler: msvc
+# 
+#   - pg: 10.23-1
+#     PlatformToolset: v120
+#     Configuration: Release
+#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
+#     rversion: 4.1.3
+#     compiler: msvc
+# 
 
 #   # WORKS - no pgsql_sln exists
 #   # BUT better off using 2022
@@ -3110,9 +3114,9 @@ for:
       }
 
   # msys2
-  # update all - skip - postgres and r are weakly and near nothing dependent on versions
-  # - bash --login -c "pacman --noconfirm -Suy"
-  # - bash --login -c "pacman --noconfirm -Suy"
+  # update all - skip - postgres and R are weakly and near nothing dependent on versions
+  # - bash --login -c "set -e;set -x;set -v;pacman -Suy --noconfirm"
+  # - bash --login -c "set -e;set -x;set -v;pacman -Suy --noconfirm"
   #
   # just in case I need this
   # - bash --login -c "pacman --noconfirm -S --needed mingw-w64-${OSBitVersion}-icu"
@@ -3190,6 +3194,9 @@ for:
   # Make %x64% available for caching
   # a variable used in the Appveyor cache area must be defined in the init
   - ps: |
+      # Defaults
+      if ("${env:Platform}"      -eq "") {${env:Platform}      = "x64"}
+      if ("${env:Configuration}" -eq "") {${env:Configuration} = "Release"}
       if ("$env:Platform" -eq "x64") {
         $env:pf = "$env:ProgramFiles"
         $env:x64 = "-x64"
@@ -3288,6 +3295,16 @@ for:
 
   - SET sed=C:\msys64\usr\bin\sed
 
+  # On some Appveyor images "Git for Windows" slips in front of MSYS2
+  - ps: |
+      if ("${env:Platform}" -eq "x64") {
+        ${env:PATH} = "C:\msys64\usr\bin;${env:PATH}"
+      } else {
+        ${env:PATH} = "C:\msys32\usr\bin;${env:PATH}"
+      }
+      which grep
+      which sed
+
   # Appveyor specific: seems not required - with Appveyor - Strawberry perl is already in the path
   # ActiveState Perl is good, but Strawberry Perl is preferred
   #
@@ -3302,6 +3319,8 @@ for:
       which perl
       ${env:PATH} = "${env:PATH};c:\${env:betterperl}\c\bin"
       which pexports
+      which grep
+      which sed
 
   #
   # if "githubcache: true",
@@ -3387,7 +3406,6 @@ for:
       # notmatch - if no "dot is found" in pg name, then pg is a: git: branch, tag, or commit.
       if (("${env:pggithubbincacheextracted}" -eq "false") -and ("${env:pg}" -notmatch "[.]")) {
         git config --global advice.detachedHead false
-        $env:PATH += ";C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64"
         #
         # git branch or commit - alphanumeric and all lowercase letters (slower download)
         #
@@ -3543,6 +3561,12 @@ for:
   # prevents building if Microsoft Visual Studio is the version 2019 and greater.
   #
   - if exist C:\projects\postgresql\pgsql.sln (
+      bash --login -c "set -e;set -x;set -v;pacman -S grep --noconfirm" &
+      which grep &
+      grep --version &
+      bash --login -c "set -e;set -x;set -v;acman  -S sed --noconfirm" &
+      which sed &
+      sed -- version &
       echo REMOVE plr ENTRY from pgsql.sln &
       echo FILE BEFORE clean_pgsql_sln.sh C:\projects\postgresql\pgsql.sln &
       type      C:\projects\postgresql\pgsql.sln &
