make  `test-cpu_info_test_cortex_a76_adj` look much like `ubuntu-arm`

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -447,10 +447,11 @@ jobs:
             # verify account has sudo rights
             sudo apt update
             sudo apt upgrade -y
+            export PG=18
             # postgresql-17 postgresql-common  postgresql-common-dev
-            sudo apt install -y postgresql postgresql-contrib
-            # To confirm that Post­greSQL started suc­cess­ful­ly, check its service status
-            sudo systemctl status postgresql
+            sudo apt install -y postgresql-${PG}
+            ## # To confirm that Post­greSQL started suc­cess­ful­ly, check its service status
+            ## sudo systemctl status postgresql
 
             # Package libR was not found in the pkg-config search path.
             # Perhaps you should add the directory containing `libR.pc'
@@ -464,8 +465,31 @@ jobs:
             #    38 | #include "postgres.h"
             #       |          ^~~~~~~~~~~~
             # TRYING TO FIX BY TRYING TO INSTALL postgresql-server-dev
-            sudo apt install -y postgresql-server-dev-17
-            
+            sudo apt install -y postgresql-server-dev-${PG}
+            echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/${PG}/main/pg_hba.conf > /dev/null
+
+            export WHOAMI=$(whoami)
+            sudo setfacl -Rm u:postgres:rwx,d:u:${WHOAMI}:rwx ${HOME}
+            sudo pg_ctlcluster ${PG} main reload
+
+#           sudo USE_PGXS=1 make install
+#           
+#           # AFTER 18m 59s
+#           # make installcheck PGUSER=postgres || (cat regression.diffs && false)
+#           # + make installcheck PGUSER=postgres
+#           # Makefile:40: ../../src/Makefile.global: No such file or directory
+#           # make: *** No rule to make target '../../src/Makefile.global'.  Stop.
+#           # + cat regression.diffs
+#           # cat: regression.diffs: No such file or directory
+#           # Error: Process completed with exit code 1.
+#           make installcheck PGUSER=postgres || (cat regression.diffs && false)
+
+            sudo pg_lsclusters
+            export USE_PGXS=1
+            SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+            # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
             sudo USE_PGXS=1 make install
+            /usr/lib/postgresql/${PG}/bin/pg_config
             make installcheck PGUSER=postgres || (cat regression.diffs && false)
 
+            # SHOULD FOLLOW WITH CODECOVERAGE TESTING PART
