plr.h:328:33 implicit declaration of function 'tuplestore_begin_heap'
master
3/16/2026 at ~ 11:30 p.m. Eastern time
https://github.com/postgres-plr/plr/actions/runs/23177624207/job/67343250829
```
In file included from pg_conversion.c:35:
pg_conversion.c: In function ‘get_frame_tuplestore’:
plr.h:328:33: warning: implicit declaration of function ‘tuplestore_begin_heap’ [-Wimplicit-function-declaration]
  328 | #define TUPLESTORE_BEGIN_HEAP   tuplestore_begin_heap(true, false, work_mem)
      |                                 ^~~~~~~~~~~~~~~~~~~~~
pg_conversion.c:2023:20: note: in expansion of macro ‘TUPLESTORE_BEGIN_HEAP’
 2023 |         tupstore = TUPLESTORE_BEGIN_HEAP;
      |                    ^~~~~~~~~~~~~~~~~~~~~
pg_conversion.c:2023:18: warning: assignment to ‘Tuplestorestate *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2023 |         tupstore = TUPLESTORE_BEGIN_HEAP;
      |                  ^
pg_conversion.c:2125:17: warning: implicit declaration of function ‘tuplestore_puttuple’ [-Wimplicit-function-declaration]
 2125 |                 tuplestore_puttuple(tupstore, tuple);
      |                 ^~~~~~~~~~~~~~~~~~~
pg_conversion.c: In function ‘get_matrix_tuplestore’:
pg_conversion.c:2167:18: warning: assignment to ‘Tuplestorestate *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2167 |         tupstore = TUPLESTORE_BEGIN_HEAP;
      |                  ^
pg_conversion.c: In function ‘get_generic_tuplestore’:
pg_conversion.c:2229:18: warning: assignment to ‘Tuplestorestate *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2229 |         tupstore = TUPLESTORE_BEGIN_HEAP;
      |

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,15 +7,15 @@ on:
    workflow_dispatch:
 
 jobs:
-  master:
+  e5a77d87:
     runs-on: ubuntu-latest
     steps:
       - name: Echo site details
-        run: echo building master
-
+        run: echo building - Save a few bytes per CatCTup.
+ 
       - name: Checkout code
         uses: actions/checkout@v6
-
+ 
       - name: checkout postgres
         run: |
           sudo apt-get update -qq
@@ -26,7 +26,8 @@ jobs:
           sudo /etc/init.d/postgresql stop
           sudo apt-get remove --purge postgresql\*
           sudo rm -rf /etc/postgresql /var/lib/postgresql
-          git clone --depth=1 https://github.com/postgres/postgres.git
+          git clone https://github.com/postgres/postgres.git
+          git checkout e5a77d876dbb6168e3013d32198794c535f1627d
           pushd postgres
           ./configure
           make -j4
@@ -35,7 +36,7 @@ jobs:
           initdb -D data
           pg_ctl -D data -l logfile start
           popd
-
+ 
       - name: Script
         run: |
           export USE_PGXS=1
@@ -49,24 +50,17 @@ jobs:
         env:
           USE_PGXS: 1
 
-  REL_18_:
-    # SEEN SEP 2025
-    # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
-    # https://github.com/actions/runner-images
-    # noble (24.04, LTS), plucky (25.04, amd64 only)
-    # https://wiki.postgresql.org/wiki/Apt
-    # https://apt.postgresql.org/pub/repos/apt/dists/
+  50362031:
     runs-on: ubuntu-latest
     steps:
       - name: Echo site details
-        run: echo building master
-
+        run: echo building - Add all required calls to TupleDescFinalize
+ 
       - name: Checkout code
         uses: actions/checkout@v6
-
+ 
       - name: checkout postgres
         run: |
-          set -x -v -e
           sudo apt-get update -qq
           sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
           sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
@@ -75,118 +69,299 @@ jobs:
           sudo /etc/init.d/postgresql stop
           sudo apt-get remove --purge postgresql\*
           sudo rm -rf /etc/postgresql /var/lib/postgresql
-          export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_[0-9]')
-          if [ "${RET}" -gt "0" ]
-          then
-            export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_[0-9]' | tail -n 1)
-            echo -n "Release(s) are found.  Taking the last Release . . . GITTAG: ${GITTAG}"
-          else
-            export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_RC[0-9]')
-            echo "Release(s) are not found.  Trying Release Candidates."
-            if [ "${RET}" -gt "0" ]
-            then
-              export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_RC[0-9]' | tail -n 1)
-              echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . GITTAG: ${GITTAG}"
-            else
-              export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_BETA[0-9]')
-              echo "Release Candidate(s) are not found. Trying Betas."
-              if [ "${RET}" -gt "0" ]
-              then
-                export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_BETA[0-9]' | tail -n 1)
-                echo -n "Beta(s) are found. Taking the last Beta . . . GITTAG: ${GITTAG}"
-              else
-                echo "Beta(s) are not found."
-              fi
-            fi
-          fi
-          echo "GITTAG: ${GITTAG}"
-          git clone --branch $GITTAG --depth=1 https://github.com/postgres/postgres.git
+          git clone https://github.com/postgres/postgres.git
+          git checkout 503620311e3fc127708b00d4cd7eff6fd3154753
           pushd postgres
           ./configure
-          make
+          make -j4
           sudo make install
           export PATH=/usr/local/pgsql/bin:$PATH
           initdb -D data
           pg_ctl -D data -l logfile start
           popd
-
+ 
       - name: Script
         run: |
-          set -x -v -e
           export USE_PGXS=1
           export PATH=/usr/local/pgsql/bin:$PATH
           SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
           # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
           sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
           psql --version
+          R --version
           make installcheck || (cat regression.diffs && false)
         env:
           USE_PGXS: 1
 
-  build:
+  c456e391:
     runs-on: ubuntu-latest
-    env:
-      PG: ${{ matrix.pg }}
-    strategy:
-      matrix:
-        include:
-          # SEEN SEP 2025
-          # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
-          # https://github.com/actions/runner-images
-          # noble (24.04, LTS), plucky (25.04, amd64 only)
-          # https://wiki.postgresql.org/wiki/Apt
-          # https://apt.postgresql.org/pub/repos/apt/dists/
-          # ##
-          # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/
-          # Regular expression search - "Package: postgresql-18$"
-          # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/main/binary-amd64/Packages
-          - pg: 18
-          - pg: 17
-          - pg: 16
-          - pg: 15
-          - pg: 14
-          - pg: 13
-          - pg: 12
-          - pg: 11
-          - pg: 10
     steps:
       - name: Echo site details
-        run: echo PG $PG
-
+        run: echo building - Optimize tuple deformation
+ 
       - name: Checkout code
         uses: actions/checkout@v6
-
-      - name: Before Script
+ 
+      - name: checkout postgres
         run: |
-          echo Building plr with PostgreSQL $PG
-          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
-          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
           sudo apt-get update -qq
           sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
           sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
-          sudo apt-get install -qq r-base-dev acl
+          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
+          sudo R --version
           sudo /etc/init.d/postgresql stop
           sudo apt-get remove --purge postgresql\*
           sudo rm -rf /etc/postgresql /var/lib/postgresql
-          sudo apt-get install postgresql-$PG
-          sudo apt-get install postgresql-server-dev-$PG
-          echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
-          # Builds under "runner"
-          # Github Actions require elevated priviledges
-          sudo setfacl -Rm u:postgres:rwx,d:u:runner:rwx /home/runner
-          sudo pg_ctlcluster $PG main reload
-
+          git clone https://github.com/postgres/postgres.git
+          git checkout c456e39113809376f6604e720910ccd24e18e034
+          pushd postgres
+          ./configure
+          make -j4
+          sudo make install
+          export PATH=/usr/local/pgsql/bin:$PATH
+          initdb -D data
+          pg_ctl -D data -l logfile start
+          popd
+ 
       - name: Script
         run: |
-          sudo pg_lsclusters
           export USE_PGXS=1
+          export PATH=/usr/local/pgsql/bin:$PATH
           SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
           # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
-          sudo USE_PGXS=1 make install
-          /usr/lib/postgresql/$PG/bin/pg_config
+          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
           psql --version
           R --version
-          make installcheck PGUSER=postgres || (cat regression.diffs && false)
+          make installcheck || (cat regression.diffs && false)
+        env:
+          USE_PGXS: 1
+
+  c675d80d:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Echo site details
+        run: echo building - Be more careful about int vs. Oid in ecpglib.
+ 
+      - name: Checkout code
+        uses: actions/checkout@v6
+ 
+      - name: checkout postgres
+        run: |
+          sudo apt-get update -qq
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
+          sudo R --version
+          sudo /etc/init.d/postgresql stop
+          sudo apt-get remove --purge postgresql\*
+          sudo rm -rf /etc/postgresql /var/lib/postgresql
+          git clone https://github.com/postgres/postgres.git
+          git checkout c675d80d7221411689d0f8ab18386d2f517eed0c
+          pushd postgres
+          ./configure
+          make -j4
+          sudo make install
+          export PATH=/usr/local/pgsql/bin:$PATH
+          initdb -D data
+          pg_ctl -D data -l logfile start
+          popd
+ 
+      - name: Script
+        run: |
+          export USE_PGXS=1
+          export PATH=/usr/local/pgsql/bin:$PATH
+          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
+          psql --version
+          R --version
+          make installcheck || (cat regression.diffs && false)
+        env:
+          USE_PGXS: 1
+
+
+
+# master:
+#   runs-on: ubuntu-latest
+#   steps:
+#     - name: Echo site details
+#       run: echo building master
+#
+#     - name: Checkout code
+#       uses: actions/checkout@v6
+#
+#     - name: checkout postgres
+#       run: |
+#         sudo apt-get update -qq
+#         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+#         sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+#         sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
+#         sudo R --version
+#         sudo /etc/init.d/postgresql stop
+#         sudo apt-get remove --purge postgresql\*
+#         sudo rm -rf /etc/postgresql /var/lib/postgresql
+#         git clone --depth=1 https://github.com/postgres/postgres.git
+#         pushd postgres
+#         ./configure
+#         make -j4
+#         sudo make install
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         initdb -D data
+#         pg_ctl -D data -l logfile start
+#         popd
+#
+#     - name: Script
+#       run: |
+#         export USE_PGXS=1
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+#         # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+#         sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
+#         psql --version
+#         R --version
+#         make installcheck || (cat regression.diffs && false)
+#       env:
+#         USE_PGXS: 1
+
+# REL_18_:
+#   # SEEN SEP 2025
+#   # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
+#   # https://github.com/actions/runner-images
+#   # noble (24.04, LTS), plucky (25.04, amd64 only)
+#   # https://wiki.postgresql.org/wiki/Apt
+#   # https://apt.postgresql.org/pub/repos/apt/dists/
+#   runs-on: ubuntu-latest
+#   steps:
+#     - name: Echo site details
+#       run: echo building master
+#
+#     - name: Checkout code
+#       uses: actions/checkout@v6
+#
+#     - name: checkout postgres
+#       run: |
+#         set -x -v -e
+#         sudo apt-get update -qq
+#         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+#         sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+#         sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
+#         sudo R --version
+#         sudo /etc/init.d/postgresql stop
+#         sudo apt-get remove --purge postgresql\*
+#         sudo rm -rf /etc/postgresql /var/lib/postgresql
+#         export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_[0-9]')
+#         if [ "${RET}" -gt "0" ]
+#         then
+#           export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_[0-9]' | tail -n 1)
+#           echo -n "Release(s) are found.  Taking the last Release . . . GITTAG: ${GITTAG}"
+#         else
+#           export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_RC[0-9]')
+#           echo "Release(s) are not found.  Trying Release Candidates."
+#           if [ "${RET}" -gt "0" ]
+#           then
+#             export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_RC[0-9]' | tail -n 1)
+#             echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . GITTAG: ${GITTAG}"
+#           else
+#             export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_BETA[0-9]')
+#             echo "Release Candidate(s) are not found. Trying Betas."
+#             if [ "${RET}" -gt "0" ]
+#             then
+#               export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_BETA[0-9]' | tail -n 1)
+#               echo -n "Beta(s) are found. Taking the last Beta . . . GITTAG: ${GITTAG}"
+#             else
+#               echo "Beta(s) are not found."
+#             fi
+#           fi
+#         fi
+#         echo "GITTAG: ${GITTAG}"
+#         git clone --branch $GITTAG --depth=1 https://github.com/postgres/postgres.git
+#         pushd postgres
+#         ./configure
+#         make
+#         sudo make install
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         initdb -D data
+#         pg_ctl -D data -l logfile start
+#         popd
+#
+#     - name: Script
+#       run: |
+#         set -x -v -e
+#         export USE_PGXS=1
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+#         # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+#         sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
+#         psql --version
+#         R --version
+#         make installcheck || (cat regression.diffs && false)
+#       env:
+#         USE_PGXS: 1
+#
+# build:
+#   runs-on: ubuntu-latest
+#   env:
+#     PG: ${{ matrix.pg }}
+#   strategy:
+#     matrix:
+#       include:
+#         # SEEN SEP 2025
+#         # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
+#         # https://github.com/actions/runner-images
+#         # noble (24.04, LTS), plucky (25.04, amd64 only)
+#         # https://wiki.postgresql.org/wiki/Apt
+#         # https://apt.postgresql.org/pub/repos/apt/dists/
+#         # ##
+#         # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/
+#         # Regular expression search - "Package: postgresql-18$"
+#         # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/main/binary-amd64/Packages
+#         - pg: 18
+#         - pg: 17
+#         - pg: 16
+#         - pg: 15
+#         - pg: 14
+#         - pg: 13
+#         - pg: 12
+#         - pg: 11
+#         - pg: 10
+#   steps:
+#     - name: Echo site details
+#       run: echo PG $PG
+#
+#     - name: Checkout code
+#       uses: actions/checkout@v6
+#
+#     - name: Before Script
+#       run: |
+#         echo Building plr with PostgreSQL $PG
+#         sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+#         wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+#         sudo apt-get update -qq
+#         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+#         sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+#         sudo apt-get install -qq r-base-dev acl
+#         sudo /etc/init.d/postgresql stop
+#         sudo apt-get remove --purge postgresql\*
+#         sudo rm -rf /etc/postgresql /var/lib/postgresql
+#         sudo apt-get install postgresql-$PG
+#         sudo apt-get install postgresql-server-dev-$PG
+#         echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
+#         # Builds under "runner"
+#         # Github Actions require elevated priviledges
+#         sudo setfacl -Rm u:postgres:rwx,d:u:runner:rwx /home/runner
+#         sudo pg_ctlcluster $PG main reload
+#
+#     - name: Script
+#       run: |
+#         sudo pg_lsclusters
+#         export USE_PGXS=1
+#         SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+#         # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+#         sudo USE_PGXS=1 make install
+#         /usr/lib/postgresql/$PG/bin/pg_config
+#         psql --version
+#         R --version
+#         make installcheck PGUSER=postgres || (cat regression.diffs && false)
 
       - name: After Success
         # success() returns true, when none of the previous steps have failed or been canceled.
