job REL_17_

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,7 +45,7 @@ jobs:
         env:
           USE_PGXS: 1
 
-  REL_17_BETA2:
+  REL_17_:
     runs-on: ubuntu-latest
     steps:
       - name: Echo site details
@@ -62,7 +62,47 @@ jobs:
           sudo /etc/init.d/postgresql stop
           sudo apt-get remove --purge postgresql\*
           sudo rm -rf /etc/postgresql /var/lib/postgresql
-          git clone --branch REL_17_BETA2 --depth=1 https://github.com/postgres/postgres.git
+          git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_[0-9]'
+          case "$?" in
+            "0")
+              echo -n "Release(s) are found.  Taking the last Release . . . "
+              export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_[0-9]' | tail -n 1)
+              ;;
+            "1")
+              echo "Release(s) are not found.  Trying Release Candidates."
+              git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_RC[0-9]'
+              case "$?" in
+                "0")
+                  echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . "
+                  export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_RC[0-9]' | tail -n 1)
+                  ;;
+                "1")
+                  echo "Release Candidate(s) are not found. Trying Betas."
+                  git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_BETA[0-9]'
+                  case "$?" in
+                    "0")
+                      echo -n "Beta(s) are found. Taking the last Beta . . . "
+                      export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_BETA[0-9]' | tail -n 1)
+                      ;;
+                    "1")
+                      echo "Beta(s) are not found."
+                      ;;
+                    *)
+                      echo "Beta Search unknown grep error."
+                      ;;
+                  esac
+                  ;;
+                *)
+                  echo "Release Candidate Search unknown grep error."
+                  ;;
+              esac
+              ;;
+            *)
+              echo "Release Search unknown grep error."
+              ;;
+          esac
+          echo $GITTAG
+          git clone --branch $GITTAG --depth=1 https://github.com/postgres/postgres.git
           pushd postgres
           ./configure
           make
