ubuntu-risk - make it look like my successes |  windows-arm - just assign 17

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -139,182 +139,259 @@ jobs:
         env:
           USE_PGXS: 1
 
-
-  # Install RISE RISC-V Runners (Personal)
-  # Where do you want to install RISE RISC-V Runners (Personal)?
-  # Also includes public repositories (read-only). ..
-  # 1. AndreMikulec (CHOSE THIS ONE) -> (*)all\selected repositories [Install]
-  #   with these permissions:
-  #     Read access to actions and metadata
-  #     Read and write access to administration
-  #       [Install]
-  #       All set, AndreMikulec!
-  #       The RISE RISC-V Runners personal app is correctly installed on AndreMikulec.
-  #
-  #       You can now trigger GitHub Actions jobs with the 
-  #         ubuntu-24.04-riscv label and they will be picked up automatically.
-  #
-  # 2. postgres-plr (I did nothing)
-  # https://github.com/apps/rise-risc-v-runners-personal/installations/select_target
-  # https://github.com/riseproject-dev/riscv-runner-sample/blob/main/.github/workflows/hello.yml
-  # https://github.com/apps/rise-risc-v-runners-personal
-  # ubuntu-24.04-riscv
-  # RISE RISC-V Runners
-  # GitHub App
-  # https://github.com/apps/rise-risc-v-runners
-  #
-  # start(ed) with a copy of "job_18_ubuntu-24_04-arm"
-  #
-  # NOT WORKING - A WORK IN PROGRESS
-  #
   job_master_ubuntu-24_04-riscv:
     name: PG master ubuntu-24.04-riscv
     runs-on: ubuntu-24.04-riscv
     steps:
+      - name: Echo site details
+        run: echo building master
+ 
       - name: Checkout code
         uses: actions/checkout@v6
  
-      - name: Before Script
+      - name: Checkout
         run: |
           set -x -v -e
-          echo "Minimal"
-          uname -m
-          uname -a
-          cat /proc/cpuinfo
-          cat /etc/os-release
-          set +x +v +e
-          sudo apt-get update -y
-          sudo apt-get upgrade -y
-          #
-          # echo Building plr with PostgreSQL $PG
-          # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
-          # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
-          #
-          dpkg -l | grep postgres
-          # see the exact dependency tree
-          apt-cache depends postgresql
-          # see everything that would be installed
-          sudo apt-get            install --simulate postgresql
-          #
-          sudo /etc/init.d/postgresql stop
-          sudo systemctl stop postgresql
-          sudo apt-get --purge    remove "postgresql*" -y
-          sudo apt-get --purge    remove libpq5 libpq-dev -y
-          sudo apt-get --dry-run  autoremove -y
-          sudo apt-get            autoremove --purge -y
-          sudo apt-get            autoclean -y
-          sudo apt-get            clean -y
-          #
-          sudo rm -rf /etc/postgresql/
-          sudo rm -rf /var/lib/postgresql/
-          sudo rm -rf /var/log/postgresql/
-          sudo rm -rf /etc/postgresql-common/
-          #
-          sudo userdel -r postgres
-          sudo groupdel postgres
-          #
-          # debconf unable to initialize frontend Dialog
+
           export DEBIAN_FRONTEND=noninteractive
-          #
           # To build PostgreSQL and its C client library (libpq) from source
-          sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libssl-dev -y
-          # default PostgreSQL client development libraries on Ubuntu
-          #   to be able to make the client-side pg_config utility to be at /usr/bin/pg_config
-          # sudo apt-get install libpq-dev -y
-          # cluster management utilities
-          # sudo apt-get install postgresql-common -y
+          sudo apt-get install --qq build-essential libreadline-dev zlib1g-dev flex bison libssl-dev -y
           git clone --branch master --depth 1 https://github.com/postgres/postgres.git postgres-src
           pushd postgres-src
           git checkout master
           ./configure --help
           ./configure --without-icu --without-readline --without-zlib --disable-rpath --enable-depend
-          make -j4
+          make 
           sudo make install
-          #
-          sudo adduser postgres
-          sudo mkdir -p /usr/local/pgsql/data
-          sudo chown postgres /usr/local/pgsql/data
-          #
-          sudo su - postgres
-          #
           export PATH=/usr/local/pgsql/bin:$PATH
+          # andre added
           export PATH=/usr/local/pgsql/lib:${PATH}
           export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
-          export PGDATA=/usr/local/pgsql/data
-          export PGUSER=postgres
-          #  postgres (PostgreSQL) 20devel
-          postgres --version
-          # PostgreSQL 20devel
-          pg_config --version
-          pg_config
-          # BINDIR = /usr/local/pgsql/bin
-          # DOCDIR = /usr/local/pgsql/share/doc
-          # HTMLDIR = /usr/local/pgsql/share/doc
-          # INCLUDEDIR = /usr/local/pgsql/include
-          # PKGINCLUDEDIR = /usr/local/pgsql/include
-          # INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
-          # LIBDIR = /usr/local/pgsql/lib
-          # PKGLIBDIR = /usr/local/pgsql/lib
-          # LOCALEDIR = /usr/local/pgsql/share/locale
-          # MANDIR = /usr/local/pgsql/share/man
-          # SHAREDIR = /usr/local/pgsql/share
-          # SYSCONFDIR = /usr/local/pgsql/etc
-          # PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
-          # CONFIGURE =  '--without-icu' '--without-readline' '--without-zlib' '--disable-rpath' '--enable-depend'
-          # CC = gcc
-          # CPPFLAGS = -D_GNU_SOURCE
-          # CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wmissing-format-attribute -Wold-style-declaration -Wimplicit-fallthrough=5 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -Wstrict-prototypes -Wold-style-definition
-          # CFLAGS_SL = -fPIC
-          # LDFLAGS = -Wl,--as-needed
-          # LDFLAGS_EX = 
-          # LDFLAGS_SL = 
-          # LIBS = -lpgcommon -lpgport -lm 
-          # VERSION = PostgreSQL 20devel
-          initdb
-          pg_ctl -l logfile start
-          psql --version
+          #
+          initdb -D data
+          pg_ctl -D data -l logfile start
           psql -d postgres -c "SELECT version();"
           psql -d postgres -c "SELECT current_setting('server_version_num');"
           popd
-          #
-          # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
-          # sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
-          # sudo apt-get install r-base-dev acl
-          #
+
           sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
           #
           # https://rstudio.github.io/r-manuals/r-admin/Obtaining-R.html
-          sudo apt install subversion -y
+          sudo apt-get install -qq subversion -y
           # r-devel
           svn checkout https://svn.r-project.org/R/trunk/ r-src
           pushd r-src
           ./configure --help
           ./configure --enable-R-shlib --disable-java --disable-byte-compiled-packages --disable-rpath --without-ICU --without-recommended-packages
-          make -j4
+          make
           sudo make install
           popd
           export PATH=/usr/local/bin:$PATH
           R --version
+          popd
 
       - name: Script
         run: |
-          sudo su - postgres
-          #
+          set -x -v -e
           export PATH=/usr/local/pgsql/bin:$PATH
+          # andre added
           export PATH=/usr/local/pgsql/lib:${PATH}
           export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
-          export PGDATA=/usr/local/pgsql/data
-          export PGUSER=postgres
-          #
-          USE_PGXS=1 SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
-          sudo make install
+          # andre added
+          export PATH=/usr/local/bin:$PATH
+          
+          export USE_PGXS=1
+          export PATH=/usr/local/pgsql/bin:$PATH
+          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
           make installcheck || (cat regression.diffs && false)
+        env:
+          USE_PGXS: 1
 
       - name: After Success
         # success() returns true, when none of the previous steps have failed or been canceled.
         if: ${{ success() }}
         # Uploads code coverage to codecov.io
         run: bash <(curl -s https://codecov.io/bash)
+
+
+
+# # Install RISE RISC-V Runners (Personal)
+# # Where do you want to install RISE RISC-V Runners (Personal)?
+# # Also includes public repositories (read-only). ..
+# # 1. AndreMikulec (CHOSE THIS ONE) -> (*)all\selected repositories [Install]
+# #   with these permissions:
+# #     Read access to actions and metadata
+# #     Read and write access to administration
+# #       [Install]
+# #       All set, AndreMikulec!
+# #       The RISE RISC-V Runners personal app is correctly installed on AndreMikulec.
+# #
+# #       You can now trigger GitHub Actions jobs with the 
+# #         ubuntu-24.04-riscv label and they will be picked up automatically.
+# #
+# # 2. postgres-plr (I did nothing)
+# # https://github.com/apps/rise-risc-v-runners-personal/installations/select_target
+# # https://github.com/riseproject-dev/riscv-runner-sample/blob/main/.github/workflows/hello.yml
+# # https://github.com/apps/rise-risc-v-runners-personal
+# # ubuntu-24.04-riscv
+# # RISE RISC-V Runners
+# # GitHub App
+# # https://github.com/apps/rise-risc-v-runners
+# #
+# # start(ed) with a copy of "job_18_ubuntu-24_04-arm"
+# #
+# # NOT WORKING - A WORK IN PROGRESS
+# #
+# job_master_ubuntu-24_04-riscv:
+#   name: PG master ubuntu-24.04-riscv
+#   runs-on: ubuntu-24.04-riscv
+#   steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v6
+#
+#     - name: Before Script
+#       run: |
+#         set -x -v -e
+#         echo "Minimal"
+#         uname -m
+#         uname -a
+#         cat /proc/cpuinfo
+#         cat /etc/os-release
+#         set +x +v +e
+#         sudo apt-get update -y
+#         sudo apt-get upgrade -y
+#         #
+#         # echo Building plr with PostgreSQL $PG
+#         # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+#         # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+#         #
+#         dpkg -l | grep postgres
+#         # see the exact dependency tree
+#         apt-cache depends postgresql
+#         # see everything that would be installed
+#         sudo apt-get            install --simulate postgresql
+#         #
+#         sudo /etc/init.d/postgresql stop
+#         sudo systemctl stop postgresql
+#         sudo apt-get --purge    remove "postgresql*" -y
+#         sudo apt-get --purge    remove libpq5 libpq-dev -y
+#         sudo apt-get --dry-run  autoremove -y
+#         sudo apt-get            autoremove --purge -y
+#         sudo apt-get            autoclean -y
+#         sudo apt-get            clean -y
+#         #
+#         sudo rm -rf /etc/postgresql/
+#         sudo rm -rf /var/lib/postgresql/
+#         sudo rm -rf /var/log/postgresql/
+#         sudo rm -rf /etc/postgresql-common/
+#         #
+#         sudo userdel -r postgres
+#         sudo groupdel postgres
+#         #
+#         # debconf unable to initialize frontend Dialog
+#         export DEBIAN_FRONTEND=noninteractive
+#         #
+#         # To build PostgreSQL and its C client library (libpq) from source
+#         sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libssl-dev -y
+#         # default PostgreSQL client development libraries on Ubuntu
+#         #   to be able to make the client-side pg_config utility to be at /usr/bin/pg_config
+#         # sudo apt-get install libpq-dev -y
+#         # cluster management utilities
+#         # sudo apt-get install postgresql-common -y
+#         git clone --branch master --depth 1 https://github.com/postgres/postgres.git postgres-src
+#         pushd postgres-src
+#         git checkout master
+#         ./configure --help
+#         ./configure --without-icu --without-readline --without-zlib --disable-rpath --enable-depend
+#         make -j4
+#         sudo make install
+#         #
+#         sudo adduser postgres
+#         sudo mkdir -p /usr/local/pgsql/data
+#         sudo chown postgres /usr/local/pgsql/data
+#         #
+#         sudo su - postgres
+#         #
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         export PATH=/usr/local/pgsql/lib:${PATH}
+#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
+#         export PGDATA=/usr/local/pgsql/data
+#         export PGUSER=postgres
+#         #  postgres (PostgreSQL) 20devel
+#         postgres --version
+#         # PostgreSQL 20devel
+#         pg_config --version
+#         pg_config
+#         # BINDIR = /usr/local/pgsql/bin
+#         # DOCDIR = /usr/local/pgsql/share/doc
+#         # HTMLDIR = /usr/local/pgsql/share/doc
+#         # INCLUDEDIR = /usr/local/pgsql/include
+#         # PKGINCLUDEDIR = /usr/local/pgsql/include
+#         # INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
+#         # LIBDIR = /usr/local/pgsql/lib
+#         # PKGLIBDIR = /usr/local/pgsql/lib
+#         # LOCALEDIR = /usr/local/pgsql/share/locale
+#         # MANDIR = /usr/local/pgsql/share/man
+#         # SHAREDIR = /usr/local/pgsql/share
+#         # SYSCONFDIR = /usr/local/pgsql/etc
+#         # PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
+#         # CONFIGURE =  '--without-icu' '--without-readline' '--without-zlib' '--disable-rpath' '--enable-depend'
+#         # CC = gcc
+#         # CPPFLAGS = -D_GNU_SOURCE
+#         # CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wmissing-format-attribute -Wold-style-declaration -Wimplicit-fallthrough=5 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -Wstrict-prototypes -Wold-style-definition
+#         # CFLAGS_SL = -fPIC
+#         # LDFLAGS = -Wl,--as-needed
+#         # LDFLAGS_EX = 
+#         # LDFLAGS_SL = 
+#         # LIBS = -lpgcommon -lpgport -lm 
+#         # VERSION = PostgreSQL 20devel
+#         initdb
+#         pg_ctl -l logfile start
+#         psql --version
+#         psql -d postgres -c "SELECT version();"
+#         psql -d postgres -c "SELECT current_setting('server_version_num');"
+#         popd
+#         #
+#         # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+#         # sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+#         # sudo apt-get install r-base-dev acl
+#         #
+#         sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
+#         #
+#         # https://rstudio.github.io/r-manuals/r-admin/Obtaining-R.html
+#         sudo apt install subversion -y
+#         # r-devel
+#         svn checkout https://svn.r-project.org/R/trunk/ r-src
+#         pushd r-src
+#         ./configure --help
+#         ./configure --enable-R-shlib --disable-java --disable-byte-compiled-packages --disable-rpath --without-ICU --without-recommended-packages
+#         make -j4
+#         sudo make install
+#         popd
+#         export PATH=/usr/local/bin:$PATH
+#         R --version
+#
+#     - name: Script
+#       run: |
+#         sudo su - postgres
+#         #
+#         export PATH=/usr/local/pgsql/bin:$PATH
+#         export PATH=/usr/local/pgsql/lib:${PATH}
+#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
+#         export PGDATA=/usr/local/pgsql/data
+#         export PGUSER=postgres
+#         #
+#         USE_PGXS=1 SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+#         sudo make install
+#         make installcheck || (cat regression.diffs && false)
+#
+#     - name: After Success
+#       # success() returns true, when none of the previous steps have failed or been canceled.
+#       if: ${{ success() }}
+#       # Uploads code coverage to codecov.io
+#       run: bash <(curl -s https://codecov.io/bash)
 
   job_18_ubuntu-24_04-arm:
     name: PG 18 ubuntu-24.04-arm
